monosec/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, RadioField
from wtforms.validators import DataRequired, Length, InputRequired
from monosec.auth.validations import validate_input

'''
Form for creating new posts
'''
class CreatePost(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=8, max=200)])
    details = TextAreaField('Details', validators=[DataRequired(), Length(min=8, max=300)])
    submit = SubmitField('Add')

    '''
    Method to validate the post title
    '''
    def validate_title(self,title):
        validate_input(title.data)

    '''
    Method to validate the text input for issues
    '''
    def validate_details(self,details):
        validate_input(details.data)

'''
Form for updating an already existing post
'''
class UpdatePost(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=8, max=200)])
    details = TextAreaField('Details', validators=[DataRequired(), Length(min=8, max=300)])
    status = RadioField('Status', choices=[('True', 'Open'), ('False', 'Closed')], validators=[InputRequired()])
    submit = SubmitField('Update')
    
    '''
    Method to validate the post title
    '''
    def validate_title(self,title):
        validate_input(title.data)

    '''
    Method to validate the text input for issues
    '''
    def validate_details(self,details):
        validate_input(details.data)

'''
Form for adding comments to a post
'''
class AddComments(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=8, max=200)])
    details = StringField('Comment', validators=[DataRequired(), Length(min=8, max=200)])
    submit = SubmitField('Add')

    '''
    Method to validate the comment title
    '''
    def validate_title(self,title):
        validate_input(title.data)
        
    '''
    Method to validate the text input for comments
    '''
    def validate_details(self,details):
        validate_input(details.data)

monosec/posts/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, abort, request, session, current_app
from flask_login import login_user, current_user, logout_user, login_required
from monosec.models import Posts, Comments, Users
from monosec.posts.forms import CreatePost, AddComments, UpdatePost
from monosec import db

posts = Blueprint('posts',__name__)

'''
Route for main portal view that lists all the issues created by the user
Admin can see all the posts, edit or delete them
Enterprise user can see all the posts, and add comments
'''
@posts.route("/portal")
@login_required
def portal():
    current_app.logger.info("Initiating portal now")
    if not current_user.is_authenticated and session['user'] != current_user.id:
        flash("Need authorization to view the page", 'error')
        logout_user()
        current_app.logger.warning("User not authorized, redirecting " + str(current_user.id))
        return redirect(url_for('auth.reset_request'))
    if not current_user.active:
        flash("Need authorization to view the page", 'error')
        current_app.logger.warning("User not active, redirecting " + str(current_user.id))
        return redirect(url_for('main.home'))
        
    # Get the posts now (based on organizatin user or external user we filter the results)
    all_posts = None
    if current_user.org_user:
        current_app.logger.warning("User is an internal user" + str(current_user.id))
        all_posts = Posts.query.all()
    else:
        current_app.logger.warning("User is an external user" + str(current_user.id))
        all_posts = Posts.query.filter_by(user_id=current_user.id).all()            
    return render_template('portal.html',posts=all_posts, admin = current_user.admin, name = current_user.name)
    
    
'''
Route for creating a new post
'''
@posts.route("/create_post",methods=['GET', 'POST'])
@login_required
def create_post():
    current_app.logger.info("Initiaiting create post - " + str(current_user.id))
    if not current_user.is_authenticated and session['user'] != current_user.id:
        flash("Need authorization to view the page", 'error')
        logout_user()
        return redirect(url_for('main.home'))
    create_post_form = CreatePost()
    if request.method == 'POST':
        if create_post_form.validate_on_submit():
            post_title = (create_post_form.title.data).strip()
            post_content = (create_post_form.details.data).strip()
            new_post = Posts(title=post_title, content=post_content, author=current_user)
            db.session.add(new_post)
            db.session.commit()
            flash("Issue added sucessfully", 'success')
            current_app.logger.info("Post created " + new_post.title)
            return redirect(url_for('posts.portal'))
    return render_template('create_post.html', form = create_post_form, title='Create New Post')
    
'''
Route for seeing the details of a post
'''
@posts.route("/post/<int:post_id>")
@login_required
def post(post_id):
    current_app.logger.info("Retrieving post details for post - " + str(post_id))
    if not current_user.is_authenticated and session['user'] != current_user.id:
        flash("Need authorization to view the page", 'error')
        logout_user()
        return redirect(url_for('main.home'))
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    post = Posts.query.get_or_404(post_id)
    user = Users.query.get(current_user.id)
    if not user.admin and not user.org_user:
        if post.author != current_user:
            current_app.logger.warning("Post author is not current user")
            abort(403)
    current_app.logger.info("User permitted to view post - " + str(current_user.id))
    current_post = Posts.query.get_or_404(post_id)
    user = Users.query.get(current_user.id)
    if current_post:
        return render_template('post.html', post=current_post, user=user)
    
    
'''
Route for updating a post
'''
@posts.route("/update_post/<int:post_id>",methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    current_app.logger.info("Updating post - " + str(post_id))
    if not current_user.is_authenticated and session['user'] != current_user.id:
        flash("Need authorization to view the page", 'error')
        logout_user()
        return redirect(url_for('main.home'))
    user = Users.query.get(current_user.id)
    post = Posts.query.get_or_404(post_id)
        
    if user and post:
        if not user.admin and not user.org_user:
            if post.author != current_user:
                current_app.logger.warning("Post author is not current user, Cannot update" + str(current_user.id))
                abort(403)
        current_app.logger.info("User permitted to edit post - " + str(current_user.id))      
        update_post_form = UpdatePost()
        if request.method == 'POST':
            if update_post_form.validate_on_submit():
                post.title = (update_post_form.title.data).strip()
                post.content = (update_post_form.details.data).strip()
                if update_post_form.status.data == 'True':
                    post.status = 1
                else:
                    post.status = 0
                db.session.commit()
                flash('Post has been updated', 'success')
                current_app.logger.info("Post has been updated'- " + str(post_id))
                return redirect(url_for('posts.portal'))
        elif request.method == 'GET':
            current_app.logger.info("Getting details of post - " + str(post_id))
            update_post_form.title.data = post.title
            update_post_form.details.data = post.content
            update_post_form.submit.label.text = 'Update Post'
    return render_template('update_post.html', title='Update Post', form = update_post_form, user = user)

'''
Route for seeing all the comments for a specific post
the user who has creaed the post can view the comments
Enterprise admin or users can see these comments as well and add new comments
'''
@posts.route("/comments/<int:post_id>")
@login_required
def comments(post_id):
    current_app.logger.info("Getting all comments for " + str(post_id))
    if not current_user.is_authenticated and session['user'] != current_user.id:
        flash("Need authorization to view the page", 'error')
        logout_user()
        current_app.logger.warning("User is not authorized to view comments " + str(current_user.id))
        return redirect(url_for('main.home'))
        
    post = Posts.query.get_or_404(post_id)
    user = Users.query.get(current_user.id)
    if not user.admin and not user.org_user:        
        if post.author != current_user:
            current_app.logger.warning("Post author is not current user, Cannot view comments" + str(current_user.id))
            abort(403)
    current_app.logger.info("User permitted to view the post comments for post - " + str(post_id))
    all_post_comments= Comments.query.filter_by(post_id=post_id).all()
    return render_template('comments.html',comments=all_post_comments, post_id=post_id)
    

'''
Route for adding comments to a specific post
the user who has creaed the post can add  comments
Enterprise admin or users can also add new comments
'''
@posts.route("/add_comment/<int:post_id>",methods=['GET', 'POST'])
@login_required
def add_comment(post_id):
    current_app.logger.info("Adding comments to post " + str(post_id))
    if not current_user.is_authenticated and session['user'] != current_user.id:
        flash("Need authorization to view the page", 'error')
        logout_user()
        current_app.logger.warning("User is not authorized to view comments " + str(current_user.id))
        return redirect(url_for('main.home'))
        
    user = Users.query.get(current_user.id)
    post = Posts.query.get(post_id)
    if not user.admin and not user.org_user:
        if post.author != current_user:
            current_app.logger.warning("Post author is not current user, Cannot view comments" + str(current_user.id))
            abort(403)
    add_comment_form = AddComments()
    if request.method == 'POST':
        if add_comment_form.validate_on_submit():
            current_post = Posts.query.get_or_404(post_id)
            #Posts.query.filter_by(id=post_id).all()
            if current_post:
                comment_title = (add_comment_form.title.data).strip()
                comment_text = (add_comment_form.title.data).strip()
                new_comment = Comments(title=comment_title, text=comment_text, post_id=post_id ,author=current_user)
                db.session.add(new_comment)
                db.session.commit()
                flash("Comment added sucessfully", 'success')
                current_app.logger.info("Comment added sucessfully to post - " + str(post_id) + " by user - " + str(current_user.id))
            else:
                current_app.logger.error("No post found for - " + str(post_id))                    
            return redirect(url_for('posts.comments', post_id=post_id))
    return render_template('add_comment.html', form = add_comment_form)
    
    

monosec/templates/add_comment.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Add Post{% endblock %}</title>
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add comment to post -</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.details.label(class="form-control-label") }}
                    {% if form.details.errors %}
                        {{ form.details(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.details.errors | safe %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.details(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

monosec/templates/auth.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Auth{% endblock %}</title>
{% block content %}
<h1>User Registration - Authentication</h1>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }} 
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Please enter the authentication token sent to the mail id used for Registration.</legend>
            <div class="form-group">
                {{ form.auth_token.label(class="form-control-label") }}

                {% if form.auth_token.errors %}
                    {{ form.auth_token(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.auth_token.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.auth_token(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

monosec/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Meta Character Set-->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <title>{% block title %}Home{% endblock %}</title>
    </head>

    <body>
        <header class="page-header">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar">
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" id="home" href="{{ url_for('main.home') }}">Home</a>
                            <a class="nav-item nav-link" id="home" href="{{ url_for('posts.portal') }}">Portal</a>                             
                            <a class="nav-item nav-link" id="add_post" href="{{ url_for('posts.create_post') }}">Add Post</a>
                            <a class="nav-item nav-link" id="logout" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" id="home" href="{{ url_for('main.home') }}">Home</a>                            
                            <a class="nav-item nav-link" id="register" href="{{ url_for('users.register') }}">Register</a>
                            <a class="nav-item nav-link" id="login" href="{{ url_for('users.login') }}">Login</a>  
                        {% endif %}          
                    </div>
                </div>
            </nav>
        </header>
        
        <main role="main" class="container" >
            <div>
                {% with messages = get_flashed_messages(with_categories=true)%}
                    {% if messages%}
                        {% for category, message in messages%}
                            {% if category == 'error' %}
                                <div class="alert alert-danger alter-dismissable fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                {% else %}
                                <div class="alert alert-success alter-dismissable fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                            {% endif %} 
                        {%endfor%}
                    {% endif%}
                {% endwith%}
                {% block content %}             
                {% endblock %}
            </div>
            
           
        </main>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous" ></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    </body>
    <nav class="navbar sticky-bottom bg-dark fixed-bottom">
        <div class="container-fluid">
          <a class="navbar-nav">Web Application - NCI - Secure Programming for Web (2022)</a>
        </div>
      </nav>
    
</html>

monosec/templates/comments.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Comment Details{% endblock %}</title>

{% block content %}
    <h1>Welcome to MonoSec Customer Querries Comments Portal</h1>
    <br>
    {% if (comments is defined) and comments %}
      <table class="table table-success table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>User</th>
            <th>Date</th>
            <th>Content</th>
          </tr>
        </thead>
        <tbody>
          {% for comment in comments %}
          <tr>
            <td>{{comment.title}}</td>
            <td>{{comment.author.name}}</td>
            <td>{{comment.date.strftime('%Y-%m-%d')}}</td>
            <td>{{comment.text}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>      
    {% else %}
      <h1>You have not added comments yet. Please add  a comment using <a href=" {{ url_for('posts.add_comment', post_id=post_id)}}">AddComment</a> </h1> 
    {% endif %}     
    <div>
      {% if current_user.is_authenticated %}
        <a class="nav-item nav-link" id="add_post" href="{{ url_for('posts.add_comment', post_id=post_id) }}">Add Comment</a>
      {% endif %}
    </div>
{% endblock content %}

monosec/templates/delete_user.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Delete User{% endblock %}</title>

{% block content %}
<h1>User Details</h1>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }} 
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ title }}</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>     
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                {{ form.cancel(class="btn btn-outline-info") }}
            </div>         
        </fieldset>
    </form>
</div>
{% endblock content %}

monosec/templates/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-dark text-muted fixed-bottom">
    
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-3">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Monosec Inc.
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>            
          </div>
          <!-- Grid column -->
  
          
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2022 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MonoSec.it</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

monosec/templates/home.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Home{% endblock %}</title>
{% block content %}
    <h1 class="cover-heading">Welcome to MonoSec Support Portal.</h1>
    <br></br>
    <p class="lead"> This is a support portal to help our customer to create requests, tickets and escalations.</p>
    <p class="lead"> Please "Login", to create / view your requests.</p>
    <p class="lead"> If not registered, please use the "Register" link above to get started.</p>

    
{% endblock content %}

monosec/templates/login.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Login{% endblock %}</title>
{% block content %}
    <h1>Welcome to Login</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login with registered email.</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div>
                    {% for error in form.recaptcha.errors %}
                        {{ error }}
                    {% endfor %}
                    {{ form.recaptcha }}
                </div>
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}                
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Do not have an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
                </small>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Trouble logging in? <a class="ml-2" href="{{ url_for('creds.reset_request') }}">Reset Password</a>
                </small>
            </div>
            
            
        </form>
    </div>
    <br>
    <div>
        <h2>Login Using Google SSO - <a class="ml-2" href="{{ url_for('users.sso_login') }}">Google-Login</a></h2>
    </div>
{% endblock content %}

monosec/templates/logout.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Logout{% endblock %}</title>
{% block content %}
    <h1>You have logged out now.</h1>
{% endblock content %}

monosec/templates/manage_users.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - User Management{% endblock %}</title>
{% block content %}
{% if (users is defined) and users %}

<table class="table table-success table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Active</th>
        <th>Internal User</th>        
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td><a href=" {{ url_for('users.user_details', user_id=user.id)}}">{{user.name}}</a></td>
        <td>{{ user.email}}</td>
        <td>{{user.active}}</td>
        <td>{{user.org_user}}</td>        
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%else%}
<h2>No users found</h2>
{%endif%}
{% endblock content %}

monosec/templates/post.html
{% extends "base.html"%}
<title>{% block title %}MonoSec - Post Details{% endblock %}</title>

{% block content %}
<h1>MonoSec Customer Querries 'Posts Portal'</h1>
<article class="media content-section">
    <br>
    <div class="media-body">
        <h2 class="article-title">{{ post.title }}</h2>
        <div class="article-metadata">
            <p class="article-content">Created By - </a>
            <a class="mr-2" href="#">{{ post.author.name }}</a>
            <p class="article-content">Creation Date - {{ post.creation_date.strftime('%Y-%m-%d') }}</p>
            <p class="article-content">Detail - {{ post.content }}</p>
        </div>
    </div>
</article>
<!-- Modal -->
{% if (post.author == current_user) or (user.admin==True) %}
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
</div>
{% endif %}
{% endblock content %}

monosec/templates/update_post.html
{% extends "base.html"%}
<title>{% block title %}{{ title }}{% endblock %}</title>
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }} 
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ title }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.details.label(class="form-control-label") }}
                    {% if form.details.errors %}
                        {{ form.details(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.details.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.details(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.status.label(class="form-control-label") }}
                    {% if form.status.errors %}
                        {{ form.status(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.status.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.status(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}